version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: challengedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - network

  cursos-ms:
    build:
      context: ./cursos-ms
    container_name: cursos-ms
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challengedb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD:


  estudiantes-ms:
    build:
      context: ./estudiantes-ms
    container_name: estudiantes-ms
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challengedb
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - cursos-ms
      - estudiantes-ms
      - keycloak
    networks:
      - network

  keycloak:
    image: jboss/keycloak
    ports:
      - "8083:8083"
    networks:
      - network
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  eureka:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    networks:
      - network

networks:
  network: