version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: challengedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  cursos-ms:
    build:
      context: ./cursos-ms
    container_name: cursos-ms
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - postgres
      - estudiantes-ms
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  estudiantes-ms:
    build:
      context: ./estudiantes-ms
    container_name: estudiantes-ms
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - postgres
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka
      - cursos-ms
      - estudiantes-ms
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  eureka:
    image: springcloud/eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_PREFERIPADDRESS=true

  config:
    image: springcloud/configserver
    container_name: config
    depends_on:
      - eureka
    ports:
      - "8888:8888"
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
#
#  keycloak:
#    image: jboss/keycloak
#    ports:
#      - "8083:8083"
#
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#

