version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: challenge_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - network

  cursos-ms:
    build:
      context: ./cursos-service
    container_name: cursos-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - network

  estudiantes-ms:
    build:
      context: ./estudiantes-service
    container_name: estudiantes-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - cursos-service
      - estudiantes-service

  keycloak:
    image: jboss/keycloak
    ports:
      - "8083:8083"
    networks:
      - network
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  eureka:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    networks:
      - network

networks:
  network: