spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: students-ms
          uri: lb://students-ms
          predicates:
            - Path=/students/**
        - id: courses-ms
          uri: lb://courses-ms
          predicates:
            - Path=/courses/**
      discovery:
        locator:
          enabled: true
          filters: enabled
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

