eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: cursos-ms
          uri: http://cursos-ms:8080
          predicates:
            - Path=/cursos/**
        - id: estudiantes-ms
          uri: http://estudiantes-ms:8080
          predicates:
            - Path=/estudiantes/**
  datasource:
    initialize: false
