spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: estudiantes-ms
          uri: lb://estudiantes-ms
          predicates:
            - Path=/estudiantes/**
        - id: cursos-ms
          uri: lb://cursos-ms
          predicates:
            - Path=/cursos/**
      discovery:
        locator:
          enabled: true
          filters: enabled
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

