spring:
  application:
    name: estudiantes-ms
  datasource:
    url: jdbc:postgresql://postgres:5432/challengedb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

