spring:
  application:
    name: cursos-ms
  datasource:
    url: jdbc:postgresql://postgres:5432/challengedb
    username: user
    password:
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
#      database: challengedb
#      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

springfox:
  documentation:
    swagger-ui:
      enabled: true
#    swagger:
#      v2:
#        path: /estudiantes-ms/v2/api-docs
#      groupName: Estudiantes-API
